### ISSUE TITLE
Legende graphiques

### ISSUE THREAD

**Issue by Hippotese-Deny-Fady** [hippotese/dataweb#4]
Pour la légende des graphiques, on doit écrire : (Kgf ou daN)

**Comment by Hippotese-Deny-Fady** [comment]
Dans le 3eme graphique, il y a une superposition entre les graduations de t (axe des x) et le label "daN"

**Comment by ixxie** [comment]
La légende est corrigée, mais la superposition est un problème avec la bibliothèque et je ne peux pas la corriger à l'adresse suivante
